version: "3.7"
services:
  mongodb:
    image: mongo
    volumes:
      - data:/data/db
    environment:
      MongoDb_Username: mongoadmin
      MongoDb_Password: secret
  backend:
    build: ./multi-01-starting-setup/backend
    image: 'goals-node'
    volumes:
      - ./multi-01-starting-setup/backend/logs:/app/logs
      - ./multi-01-starting-setup/backend:/app
      - /app/node_modules
    ports:
      - "2888:2888"
    env_file:
      - ./multi-01-starting-setup/.env
    depends_on:
      - mongodb
  frontend:
    build: ./multi-01-starting-setup/frontend
    image: goals-frontend
    ports: 
      - "3000:3000"
    volumes:
      - ./multi-01-starting-setup/frontend/src:/app/src
    stdin_open: true
    tty: true
    depends_on:
      - backend

volumes:
  data:
  logs: